const storedProducts = localStorage.getItem('products');
let items = storedProducts ? JSON.parse(storedProducts) : [

  { id:1, name: "Nike Dunk Low Retro", 
  img: "./images/2d1b64e2-323d-41bb-8d75-6490d90ba518.webp",
  description: "El ícono del básquetbol, creado para la cancha y adaptado al estilo urbano, vuelve con detalles clásicos y un estilo de básquetbol retro.", 
  category: "Hombre",
  quantity: 0,
  price: 115},


  { id:2, name: "Nike Tanjun",
  img: "./images/3574b192-7a10-4aa2-a084-0ff7009421d5.webp",
  description: " Confeccionado con al menos un 20% de contenido reciclado y agujetas de poliéster reciclado 100%, este modelo no pasa ningún detalle por alto.", 
  category: "Mujer",
  quantity: 0,
  price: 109},


  { id:3, name: "Jumpman Two Trey", 
  img: "./images/f6bb75e3-f86b-4031-9265-4343b1e14bd7.webp",
  description: "Esta nueva generación de Jordan celebra el tiempo de Mike en Chicago, completado con una parte superior de cuero de alta calidad y suelas Air amortiguadas.", 
  category: "Infantil",
  quantity: 0,
  price: 135},


  { id:4, name: "Air Jordan 1 Mid", 
  img: "./images/73d56d3d-b63d-4f84-812c-ef8a58385279.webp",
  description: "Inspirada en el AJ1 original, esta edición de corte mid mantiene el look icónico que te encanta, y los colores selectos y el cuero impecable le dan una identidad distintiva", 
  category: "Hombre",
  quantity: 0,
  price: 106},


  { id:5, name: "Nike Court Legacy Next Nature", 
  img: "./images/2535afe3-2a96-4f21-9bfc-1eff65930680.webp",
  description: "El cuero sintético y el diseño retro te permiten combinar el deporte con la moda. Haz el bien y luce bien.", 
  category: "Mujer",
  quantity: 0,
  price: 125},


  { id:6, name: "Nike Air Force 1 '07 EasyOn", 
  img: "./images/57558712-5ebe-4abb-9984-879f9e896b4c.webp",
  description: "Más rápido que contar hasta tres: ponte el calzado de básquetbol original en un instante y sal a la cancha sin perder tiempo.", 
  category: "Mujer",
  quantity: 0,
  price: 135},


  { id:7, name: "Nike Blazer Low '77", 
  img: "./images/f385aae2-652c-481d-a947-996b7167f4c2.webp",
  description: "El Nike Blazer Low '77 ha trascendido su propósito inicial como calzado para la cancha de básquetbol y ha llegado a la moda urbana.", 
  category: "Infantil",
  quantity: 0,
  price: 127},


  { id:8, name: "Air Jordan 1 Mid", 
  img: "./images/calzado-grandes-air-jordan-1-mid-bTcGkl.jpg",
  description: "Todas las comodidades clásicas Jordan también están ahí: Nike Air en la suela para ofrecer una pisada acolchada y una suela cupsole de goma para brindar una comodidad cotidiana.", 
  category: "Infantil", 
  quantity: 0,
  price: 135},

  { id:9, name: "TENIS FORUM LOW X THE GRINCH", 
  img: "./images/Tenis_Forum_Low_x_The_Grinch_Blanco_ID3512_06_standard.avif",
  description: "Tenis Forum de corte bajo inspirados en un gruñón querido. Descubre un estilo clásico con un toque travieso cortesía del gruñón favorito de todos: el Grinch.", 
  category: "Unisex", 
  quantity: 0,
  price: 170},

  { id:10, name: "TENIS FORUM LOW CL THE GRINCH", 
  img: "./images/Tenis_Forum_Low_CL_The_Grinch_Beige_ID8896_06_standard.avif",
  description: "Prepárate para revolucionarlo todo. Te presentamos los tenis adidas Forum inspirados en Max, el perro fiel de 'Cómo el Grinch robó la Navidad' del Dr. Seuss.", 
  category: "Unisex", 
  quantity: 0,
  price: 174},

  { id:11, name: "TENIS FORUM LOW CL THE GRINCH ROSA", 
  img: "./images/RosaTenis_Forum_Low_CL_The_Grinch_Rosa_ID8895_06_standard.avif",
  description: "Inspirados en The Grinch. La parte superior de gamuza prémium se inspira en los colores del atuendo de Cindy Lou Who.", 
  category: "Mujer", 
  quantity: 0,
  price: 174},

  { id:12, name: "TENIS RUN 60S 2.0", 
  img: "./images/Tenis_Run_60s_2.0_Negro_FZ0961_06_standard.avif",
  description: "El legado deportivo de adidas estar a flor de piel en estos tenis inspirados en el running. Fusionando lo mejor de las siluetas de las pistas de atletismo y la moda urbana moderna.", 
  category: "Hombre", 
  quantity: 0,
  price: 55},

  { id:13, name: "Nike Air Force 1 Low By You", 
  img: "./images/NikeAirForce1LowByYou.webp",
  description: "Brilla en satén, mantén el estilo clásico con lona o obtén lujo con cuero. Elijas lo que elijas, los AF1 son todo sobre ti.", 
  category: "Unisex", 
  quantity: 0,
  price: 135},

  { id:14, name: "Nike Air Force 1 '07", 
  img: "./images/NikeAirForce1'07.webp",
  description: "No hay nada más legendario que este modelo. Este original de básquetbol mezcla la comodidad de la cancha con el atractivo urbano.", 
  category: "Hombre", 
  quantity: 0,
  price: 115},

  { id:15, name: "TENIS ADIDAS GRAND COURT TD LIFESTYLE", 
  img: "./images/Tenis_adidas_Grand_Court_TD_Lifestyle_Court_Casual_Blanco_GW9250_06_standard.avif",
  description: "Es hora de agregarle un nuevo integrante a tu colección de tenis. Dale la bienvenida a estos tenis adidas Grand Court.", 
  category: "Unisex", 
  quantity: 0,
  price: 75},

  { id:16, name: "TENIS FORUM BOLD STRIPES", 
  img: "./images/Tenis_adidas_Grand_Court_TD_Lifestyle_Court_Casual_Blanco_GW9250_06_standard.avif",
  description: "Forum Bold Stripes W es un nuevo producto para Unisex de adidas. Te invitamos a ver las imágenes para apreciar más detalles desde diferentes ángulos.", 
  category: "Unisex", 
  quantity: 0,
  price: 149},

  { id:17, name: "TENIS FORUM BOLD STRIPES", 
  img: "./images/Tenis_Forum_Bold_Stripes_Negro_ID6844_06_standard.avif",
  description: "Pon tu verdadera personalidad a la vista de todos con estos tenis adidas Forum Bold Stripes. Una reconstrucción de los Forum de 1984.", 
  category: "Unisex", 
  quantity: 0,
  price: 149},

  { id:18, name: "TENIS ADIDAS GRAND COURT", 
  img: "./images/Tenis_adidas_Grand_Court_Lifestyle_para_Tenis_con_Cordones_Blanco_GW6511_06_standard.avif",
  description: "Prepáralos para seguir los pasos de los mejores jugadores de tenis. Estos tenis adidas para niños tienen un look estilizado inspirado en el estilo de las canchas de tenis de los años 70.", 
  category: "Infantil", 
  quantity: 0,
  price: 72},

  { id:19, name: "Nike Air Force 1 '07", 
  img: "./images/Nike_AirForce1'07.webp",
  description: "El fulgor vive en Nike Air Force 1'07, el ícono del básquetbol que le da un toque fresco: colores audaces y la cantidad perfecta de destellos para que brilles.", 
  category: "Hombre", 
  quantity: 0,
  price: 115},

  { id:20, name: "Nike Air Force Black 1 '07", 
  img: "./images/Nike_AirForceBlack1'07.webp",
  description: "El fulgor vive en Nike Air Force 1 '07, el ícono del básquetbol que le da un toque fresco: colores audaces y la cantidad perfecta de destellos para que brilles.", 
  category: "Hombre", 
  quantity: 0,
  price: 115},

  { id:21, name: "TENIS ADIDAS GRAND COURT", 
  img: "./images/Tenis_adidas_Grand_Court_Lifestyle_para_Tenis_con_Cordones_Blanco_GW6505_06_standard.avif",
  description: "Prepáralos para seguir los pasos de los mejores jugadores de tenis. Estos tenis adidas para niños tienen un look estilizado inspirado en el estilo de las canchas de tenis de los años 70.", 
  category: "Infantil", 
  quantity: 0,
  price: 72},

  { id:22, name: "Nike Dunk High Premiun", 
  img: "./images/NikeDunkHighPremiun.webp",
  description: "El estilo vintage se eleva hasta el cielo con el regreso del Nike Dunk High. El cuero premium, los detalles nuevos y el estilo inconfundible hacen que cualquier look sea un éxito.", 
  category: "Hombre", 
  quantity: 0,
  price: 135},

  { id:23, name: "Jordan 1 Low SE", 
  img: "./images/Jordan1LowSE.webp",
  description: "Celebra lo que te define con este audaz AJ1. Inspirado en el original de 1985, este par ofrece un impecable look clásico que se ve familiar, pero siempre renovado.", 
  category: "Hombre", 
  quantity: 0,
  price: 125},

  { id:24, name: "Air Jordan 3 'Fear'", 
  img: "./images/AirJordan3Fear.webp",
  description: "Impecable y supremo, el AJ3 regresa con todo su estilo y gracia de siempre. El cuero de calidad en la parte superior, con una lujosa textura de estampado de elefante.", 
  category: "Hombre", 
  quantity: 0,
  price: 210},

  { id:25, name: "TENIS ADVANTAGE", 
  img: "./images/Tenis_Advantage_Blanco_GW4845_06_standard.avif",
  description: "Añade un poco de estilo sutil a tus looks informales. El refuerzo de talón de estos tenis adidas inspirados en el tenis luce un acabado iridiscente que atraerá todas las miradas.", 
  category: "Unisex", 
  quantity: 0,
  price: 65},

  { id:26, name: "Air Jordan 5 x A Ma Maniére", 
  img: "./images/calzado-air-jordan-5-10-a-ma-maniére-CHfnZp.jpg",
  description: "Jordan y A Ma Maniére se unen de nuevo para crear una versión elegante del ya icónico AJ5. Los detalles de diseño del calzado predilecto.", 
  category: "Mujer", 
  quantity: 0,
  price: 225},

  { id:27, name: "TENIS PARK ST.", 
  img: "./images/Tenis_Park_St._Blanco_IE7446_06_standard.avif",
  description: "Sal a la calle con estilo con estos tenis adidas versátiles. Combinan un look icónico con comodidad para todo el día.", 
  category: "Mujer", 
  quantity: 0,
  price: 104},

  { id:28, name: "TENIS ADIDAS COURT SILK", 
  img: "./images/Tenis_adidas_Court_Silk_Blanco_IE2167_06_standard.avif",
  description: "Destaca tu lado creativo con estos tenis cargados de personalidad. Estos tenis adidas le inyectan nueva vida al clásico estilo de las canchas de tenis.", 
  category: "Mujer", 
  quantity: 0,
  price: 95},

  { id:29, name: "Air Jordan 1 High Method of Make", 
  img: "./images/calzado-air-jordan-1-high-method-of-make-hCCcBh.jpg",
  description: "Tu estilo es icónico y tu gusto es de primer nivel. Presúmelo con la serie Method of Make: versiones limitadas y mejoradas de un calzado legendario.", 
  category: "Mujer", 
  quantity: 0,
  price: 155},

  { id:30, name: "Air Jordan 1 Mid SE", 
  img: "./images/calzado-air-jordan-1-mid-se-P7bjRV.jpg",
  description: "El Air Jordan 1 Mid SE mantiene el atractivo atemporal del primer modelo AJ1 y lo moderniza con colores frescos para darle un perfil más actual.", 
  category: "Unisex", 
  quantity: 0,
  price: 115},

]